---
title: "A look at Quarto..."
date: "2023-07-03"
date-modified: "2023-07-08"
# draft: true
categories: [quarto, markdown, publishing, open-source]
keywords: [quarto, static site, data notebooks, markdown, scientific markdown, technical publishing, document publishing, frameworks, r, python, julia, observable js, mermaid, graphviz]
toc: true
toc-depth: 4
toc-location: right
status: draft
---

A nice (newish) option for data notebooks and&nbsp;technical publishing.  

**DRAFT**

## Summary

Quarto tidily fits the billing of "an open-source scientific and technical publishing 
system".  Announced a year ago, Quarto is the evolution of R Markdown and does quite a 
bit more than just R.  

I've been transitioning my personal notebooks to Quarto and so far it's ticking all the 
boxes.  So much so, I'm trying it out for authoring and publishing this static web&nbsp;site.

Authors write in Pandoc markdown, can switch smoothly between authoring tools or
IDEs and publish to multiple formats.  Out-of-the-box support for creating data notebooks,
dynamic content and diagrams mean very little setup for most use cases.  Another really 
nice aspect is support for multiple authoring tools including R&nbsp;Studio, VS Code, Neovim or 
any text editor via the CLI. 

So far, Quarto is really speaking to my polyglot needs.  And where it does not, custom
extensions offer a path to further tailor the experience and rendering outputs.

###

## Overview

The Quarto CLI can be installed on multiple platforms. For this overview, I've been using
a couple flavors of MacOS.

### Tools

I like switching tools based on context or device limitations.   Quarto's multi-tool 
support lets me use the tool for my current context or focus.

* R Studio
* Jupyter _Not yet tried._
* Neovim _Not yet tried_
* VS Code
* CLI


For this site, I've mostly been using VS Code, CLI or another text editor.  For my various 
management data workbooks I've been using R Studio.

<!-- TODO any note on VS Code experience for data notebooks. -->


### Authoring

Pandoc markdown extends and revises markdown syntax.  There are some syntactic shifts, but 
writing still emphasizes ease of writing and reading.

Big bonuses are:

* Diagram support out-of-the-box for graphviz and mermaid
* More robust list options

Authors can add more formatting control with Pandoc, or opt to stick with the sparer 
style of plain old markdown.


### Computations

```{r}
#| echo: true
x <- 2
```

### Tools

### Outputs & Rendering

<!-- A wide variety of rendering options based on established/stable tech (Pandoc, R Markdown, Knittr).
Interesting options for publishing to wiki's and extension system for customization

- documents like pdf, epub, doc
- html (as a website, a reveljs presentation, etc.)
- markdown (some magic here.) -->

#### Documents

#### Presentations

#### Websites

#### Books

#### Interactivity

### Publishing

#### Web::Blog

Publishing manually or via Github Actions for a PR-based workflow is pretty simple.

[Github Pages](https://quarto.org/docs/publishing/github-pages.html){target="_blank"}
[Github Actions](https://docs.github.com/en/actions){target="_blank"}


### Projects


## Experience

Things to look into or see where help is possible.

Preview/live reload -- sluggish or odd response times.


## Wish list

Things to find how to do or customize later.

* Metadata
  - Custom metadata display in articles
    - `status` I'd like to be able to create status metadata that can be displayed on page
* Custom templates and starters
* Bootstrap is a very good default, but I'd like to have more options to customize
  - Current custom theming still has bootstrap to override
  - Bootstrap template bugs
    - Search icon / menu placement, menu open jitter
* CLI command to easily create new posts or pages
* Code execution or playgrounds, more immediate wishes are for
  - JavaScript
  - Typescript
  - Rust, Wasm
  - Web graphics (or codepen embeds?)
* Global dictionary/constants for categories and keywords
* VSCode markdown formatter (break at char limits or other linting)
* System dynamics models (via R or python)

## Errata

* [Quarto litmus test](/notes/quarto/){target="_blank"} to try syntax and features

## Resources

* [https://quarto.org/](https://quarto.org/){target="_blank"}
* [https://quarto.org/docs/download/](https://quarto.org/docs/download/){target="_blank"}
* [https://quarto.org/docs/guide/](https://quarto.org/docs/guide/){target="_blank"}
* [https://quarto.org/docs/extensions/creating.html](https://quarto.org/docs/extensions/creating.html){target="_blank"}
* [https://quarto.org/docs/reference/formats/html.html](https://quarto.org/docs/reference/formats/html.html){target="_blank"}
* [https://posit.co/blog/announcing-quarto-a-new-scientific-and-technical-publishing-system/](https://posit.co/blog/announcing-quarto-a-new-scientific-and-technical-publishing-system/){target="_blank"}
* https://garrettgman.github.io/rmarkdown/authoring_pandoc_markdown.html